server:
  port: 8081

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Enable dynamic routing based on service discovery
      routes:
        # Optional manual routes
        - id: custom-route
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

        # Allows credentials

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
