server:
  port: 8081

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      discovery:
        locator:
          enabled: true  # Enable dynamic routing based on service discovery
      routes:
        # Route for user service
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

        # Route for authentication service
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/authentication/**  # Ensure this matches the endpoints in the auth service
            - Path=/otp/**

        - id: service-subscription-service
          uri: lb://SERVICE-SUBSCRIPTION-SERVICE
          predicates:
            - Path=/api/subscription/**  # Ensure this matches the endpoints in the auth service

        - id: bill-service
          uri: lb://BILL-SERVICE
          predicates:
            - Path=/bill/**  # Ensure this matches the endpoints in the auth service

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
