server:
  port: 8081

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Enable dynamic routing based on service discovery
      routes:
        # Route for user service
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

        # Route for authentication service
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/authentication/**  # Ensure this matches the endpoints in the auth service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
