
spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  application:
    name: notification-service

mail:
  host: smtp.gmail.com
  port: 587
  username: your-email@gmail.com
  password: your-email-password
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true


server:
  port: 8081  # Port on which the notification service is running

    # Unique service name for Eureka

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/